nombre = input("Ingrese su nombre: ")
apellido = input("Ingrese su apellido : ")
seccion = input ("Ingrese su seccion: ")
sede = input("Ingrese su sede : ")

print("\n---Informacion Ingresada---")
print(f"Nombre: {nombre}")
print(f"Apellido: {apellido}")
print(f"Seccion: {seccion}")
print(f"Sede: {sede}")